---
- name: include variables
  include_vars: "{{ ansible_distribution }}.yml"

- block:
  - import_tasks: gnome/packages.yml

  - import_tasks: system_setup/tweaks.yml

  - import_tasks: software/bitwarden.yml
  - import_tasks: software/discord.yml
  - import_tasks: software/google_chrome.yml
  - import_tasks: software/lutris.yml
  - import_tasks: software/slack.yml
  - import_tasks: software/spotify.yml
  - import_tasks: software/vscode.yml
  - import_tasks: software/zoom.yml
