---
- name: install ppa
  apt_repository:
    repo: 'ppa:lutris-team/lutris'
    state: present
  when:
    - ansible_distribution in ["Pop!_OS", "Ubuntu"]
    - lutris is defined
    - lutris == true

- name: install package
  package:
    state: latest
    name: lutris
  when:
    - ansible_distribution in ["Pop!_OS", "Ubuntu"]
    - lutris is defined
    - lutris == true
