---
- name: install utility packages
  package:
    state: latest
    name:
      - htop
      - lsof
      - neofetch
      - zsh
      - htop
      - vim
      - tmux
      - jq
      - wget
      - unzip
      - curl
