---
- block:
  - import_tasks: users.yml
  - import_tasks: ansible_setup.yml
  - import_tasks: software/packages_cleanup.yml
  - import_tasks: software/packages_development.yml
  - import_tasks: software/packages_pip.yml
  - import_tasks: software/packages_utilities.yml
  - import_tasks: system/clock.yml
  - import_tasks: system/locale.yml
