---
- name: add sudoers file
  copy:
    src: sudoers_andy
    dest: /etc/sudoers.d/andy
    owner: root
    group: root
    mode: 0440

- name: create .ssh directory
  file:
    path: "{{ user_home }}/.ssh"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0700

- name: create config directories
  file:
    path: "{{ user_home }}/{{ item.dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0700
  with_items:
    - { dir: '.config'}
    - { dir: '.config/nvim' }
    - { dir: '.config/nvim/autoload'}
    - { dir: '.config/nvim/plug-config' }
    - { dir: '.config/nvim/vim-plug' }
    - { dir: '.functions' }
    - { dir: '.tmux' }
    - { dir: '.tmux/config' }
    - { dir: '.zsh' }
    - { dir: 'Pictures/wallpapers'}

- name: copy dotfiles
  copy:
    src: dotfiles/{{ item.src }}
    dest: "{{ user_home }}/{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0700
  with_items:
    - { src: '.functions/docker', dest: '.functions/docker' }
    - { src: '.functions/git', dest: '.functions/git' }
    - { src: '.functions/ansible', dest: '.functions/ansible' }
    - { src: '.bash_aliases', dest: '.bash_aliases' }
    - { src: '.gitconfig', dest: '.gitconfig' }
    - { src: '.gitignore', dest: '.gitignore' }
    - { src: 'zsh/.zshrc', dest: '.zshrc' }

- name: copy zsh files
  copy:
    src: dotfiles/zsh/{{ item.src }}
    dest: "{{ user_home }}/.zsh/{{ item.src }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0700
  with_items:
    - { src: 'aliases.zsh' }
    - { src: 'completion.zsh' }

- name: copy wallpapers over
  copy:
    src: "{{ item }}"
    dest: "{{ user_home }}/Pictures/wallpapers/"
    owner: "{{ user }}"
    group: "{{ group }}"
  with_fileglob: "wallpapers/*"
