---
- name: add sudoers file
  copy:
    src: sudoers_andy
    dest: /etc/sudoers.d/andy
    owner: root
    group: root
    mode: 0440

- name: create .ssh directory
  file:
    path: /home/andy/.ssh
    state: directory
    owner: andy
    group: andy
    mode: 0700

- name: create config directories
  file:
    path: /home/andy/{{ item.dir }}
    state: directory
    owner: andy
    group: andy
    mode: 0700
  with_items:
    - { dir: '.config'}
    - { dir: '.config/nvim' }
    - { dir: '.config/nvim/autoload'}
    - { dir: '.config/nvim/plug-config' }
    - { dir: '.config/nvim/vim-plug' }
    - { dir: '.config/alacritty' }
    - { dir: '.functions' }
    - { dir: '.tmux' }
    - { dir: '.tmux/config' }
    - { dir: '.tmux/ftplugin' }
    - { dir: '.zsh' }
    - { dir: 'Pictures/wallpapers'}

- name: copy dotfiles
  copy:
    src: dotfiles/{{ item.src }}
    dest: /home/andy/{{ item.dest }}
    owner: andy
    group: andy
    mode: 0700
  with_items:
    - { src: 'dotfiles/.functions/docker', dest: '.functions/docker' }
    - { src: 'dotfiles/.functions/git', dest: '.functions/git' }
    - { src: 'dotfiles/.bash_aliases', dest: '.bash_aliases' }
    - { src: 'dotfiles/.gitconfig', dest: '.gitconfig' }
    - { src: 'dotfiles/.gitignore', dest: '.gitignore' }
    - { src: 'dotfiles/.zshrc', dest: '.zshrc' }

- name: copy zsh files
  copy:
    src: dotfiles/zsh/{{ item.src }}
    dest: /home/andy/.zsh/{{ item.src }}
    owner: andy
    group: andy
    mode: 0700
  with_items:
    - { src: 'aliases.zsh' }
    - { src: 'completion.zsh' }
    - { src: 'prompt.zsh' }

- name: copy wallpapers over
  copy:
    src: "{{ item }}"
    dest: /home/andy/Pictures/wallpapers/
  with_fileglob: "wallpapers/*"
